#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Module level constants
XXX = 1, 1, 1
X__ = 1, 0, 0
_X_ = 0, 1, 0
__X = 0, 0, 1
_XX = 0, 1, 1
X_X = 1, 0, 1
XX_ = 1, 1, 0
___ = 0, 0, 0

# Glyph library
glyphs = {
    ' ': ( ___, ___, ___, ___),
    'A': ( _X_, X_X, XXX, X_X ),
    'a': ( ___, _XX, X_X, XXX ),
    'B': ( XX_, XXX, X_X, XXX ),
    'b': ( X__, XX_, X_X, XX_ ),
    'C': ( _XX, X__, X__, _XX ),
    'c': ( ___, _XX, X__, _XX ),
    'D': ( XX_, X_X, X_X, XX_ ),
    'd': ( __X, _XX, X_X, _XX ),
    'E': ( XXX, XX_, X__, XXX ),
    'e': ( ___, XXX, X__, _XX ),
    'F': ( XXX, X__, XX_, X__ ),
    'f': ( __X, _X_, XXX, _X_ ),
    'G': ( _XX, X__, X_X, _XX ),
    'g': ( ___, XX_, X_X, XXX ),
    'H': ( X_X, X_X, XXX, X_X ),
    'h': ( X__, XXX, X_X, X_X ),
    'I': ( _X_, _X_, _X_, _X_ ),
    'i': ( ___, _X_, _X_, _X_ ),
    'J': ( XXX, __X, X_X, _X_ ),
    'j': ( ___, __X, __X, XX_ ),
    'K': ( X_X, X_X, XX_, X_X ),
    'k': ( X__, X_X, XX_, X_X ),
    'L': ( X__, X__, X__, XXX ),
    'l': ( X__, X__, X__, XX_ ),
    'M': ( XXX, XXX, X_X, X_X ),
    'm': ( ___, XXX, XXX, X_X ),
    'N': ( XX_, X_X, X_X, X_X ),
    'n': ( ___, XX_, X_X, X_X ),
    'O': ( _X_, X_X, X_X, _X_ ),
    'o': ( ___, _X_, X_X, _X_ ),
    'P': ( XX_, X_X, XX_, X__ ),
    'p': ( ___, XXX, XXX, X__ ),
    'Q': ( _X_, X_X, X_X, _XX ),
    'q': ( ___, XXX, XXX, __X ),
    'R': ( XX_, X_X, XX_, X_X ),
    'r': ( ___, XX_, X__, X__ ),
    'S': ( _XX, _X_, _X_, XX_ ),
    's': ( ___, _XX, _X_, XX_ ),
    'T': ( XXX, _X_, _X_, _X_ ),
    't': ( _X_, XXX, _X_, _XX ),
    'U': ( X_X, X_X, X_X, XXX ),
    'u': ( ___, X_X, X_X, XXX ),
    'V': ( X_X, X_X, X_X, _X_ ),
    'v': ( ___, X_X, X_X, _X_ ),
    'W': ( X_X, X_X, XXX, XXX ),
    'w': ( ___, X_X, XXX, XXX ),
    'X': ( X_X, X_X, _X_, X_X ),
    'x': ( ___, X_X, _X_, X_X ),
    'Y': ( X_X, X_X, _X_, _X_ ),
    'y': ( ___, X_X, _X_, _X_ ),
    'Z': ( XX_, _X_, _X_, _XX ),
    'z': ( ___, XX_, _X_, _XX ),
    '0': ( XXX, X_X, X_X, XXX ),
    '1': ( _XX, __X, __X, __X ),
    '2': ( XX_, _X_, X__, XXX ),
    '3': ( XXX, _XX, __X, XX_ ),
    '4': ( X_X, X_X, XXX, __X ),
    '5': ( _XX, _X_, __X, XXX ),
    '6': ( X__, XXX, X_X, XXX ),
    '7': ( XXX, __X, _X_, _X_ ),
    '8': ( _XX, XXX, X_X, XXX ),
    '9': ( XXX, X_X, XXX, __X ),
    '.': ( ___, ___, ___, _X_ ),
    '!': ( _X_, _X_, ___, _X_ ),
    '?': ( XX_, __X, ___, _X_ ),
    ':': ( ___, _X_, ___, _X_ ),
    ',': ( ___, ___, _XX, __X ),
    ';': ( __X, ___, _XX, __X ),
    "'": ( _XX, __X, ___, ___ ),
    '"': ( X_X, X_X, ___, ___ ),
    '+': ( ___, _X_, XXX, _X_ ),
    '-': ( ___, ___, XXX, ___ ),
    '/': ( __X, _X_, _X_, X__ ),
    '*': ( X_X, _X_, X_X, ___ ),
    '_': ( ___, ___, ___, XXX ),
    '(': ( _X_, X__, X__, _X_ ),
    ')': ( _X_, __X, __X, _X_ ),
    '[': ( XXX, X__, X__, XXX ),
    ']': ( XXX, __X, __X, XXX ),
    '{': ( _XX, _X_, X__, _XX ),
    '}': ( XX_, _X_, __X, XX_ ),
    '=': ( ___, XXX, ___, XXX ),
    '<': ( ___, __X, XX_, __X ),
    '>': ( ___, X__, _XX, X__ ),
    '±': ( _X_, XXX, _X_, XXX ),
    '#': ( X_X, XXX, XXX, X_X ),
    '@': ( XXX, X_X, __X, XXX ),
    '\\': ( X__, _X_, _X_, __X )
}